targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            {
              "^lib/models/{{}}.dart": "lib/generated/models/{{}}.g.dart",
            }
      json_serializable:
        generate_for:
          - lib/models/*.dart
        