name: tekio_menu
description: "This package allows you to build a complex menus with just a json file. This package is a part of the tekio plugins."
version: 0.0.3
homepage: https://github.com/tekioplugins/tekio_menu
repository: https://github.com/tekioplugins/tekio_menu

topics: 
  - json
  - widget
  - dynamic
  - menu
  

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
