name: Publish package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pub:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get dart sdk
        uses: dart-lang/setup-dart@v1
      - name: Publish package
        run: dart pub publish --force
